"""Create a baseline migrations

Revision ID: 7e33d4e83d7a
Revises: 
Create Date: 2024-04-24 10:23:20.234321

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e33d4e83d7a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_list",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uuid", sa.UnicodeText(), nullable=False),
        sa.Column("first_name", sa.UnicodeText(), nullable=False),
        sa.Column("last_name", sa.UnicodeText(), nullable=False),
        sa.Column("formatted_name", sa.UnicodeText(), nullable=False),
        sa.Column("reporting_name", sa.UnicodeText(), nullable=False),
        sa.Column("aka_name", sa.UnicodeText(), nullable=False),
        sa.Column("birth_date", sa.DateTime(), nullable=False),
        sa.Column(
            "gender_code",
            sa.Enum(
                "MALE", "FEMALE", "OTHER", name="genders", native_enum=False, length=255
            ),
            nullable=False,
        ),
        sa.Column("middle_name", sa.UnicodeText(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "user_address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("address_line_1", sa.UnicodeText(), nullable=False),
        sa.Column("address_line_2", sa.UnicodeText(), nullable=True),
        sa.Column("city", sa.UnicodeText(), nullable=False),
        sa.Column("state", sa.UnicodeText(), nullable=False),
        sa.Column("zip_code", sa.UnicodeText(), nullable=False),
        sa.Column(
            "country",
            sa.Enum(
                "USA", "CANADA", "MEXICO", name="country", native_enum=False, length=255
            ),
            nullable=False,
        ),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_list.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_address")
    op.drop_table("user")
    # ### end Alembic commands ###
