"""initial migration

Revision ID: e6595d05960d
Revises: 
Create Date: 2024-10-10 20:59:21.571167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6595d05960d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.UnicodeText(), nullable=False),
    sa.Column('last_name', sa.UnicodeText(), nullable=False),
    sa.Column('aka_name', sa.UnicodeText(), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=False),
    sa.Column('gender_code', sa.Enum('MALE', 'FEMALE', name='genders', native_enum=False, length=255), nullable=False),
    sa.Column('phone_mom', sa.UnicodeText(), nullable=True),
    sa.Column('phone_dad', sa.UnicodeText(), nullable=True),
    sa.Column('mom_name', sa.UnicodeText(), nullable=True),
    sa.Column('dad_name', sa.UnicodeText(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('belt', sa.Enum('MALE', 'FEMALE', name='genders', native_enum=False, length=255), nullable=False),
    sa.Column('notes', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.UnicodeText(), nullable=False),
    sa.Column('city', sa.UnicodeText(), nullable=False),
    sa.Column('province', sa.UnicodeText(), nullable=False),
    sa.Column('postal_code', sa.UnicodeText(), nullable=False),
    sa.Column('address_type', sa.Enum('MOM', 'DAD', 'HOME', name='addresstype', native_enum=False, length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_address')
    op.drop_table('user_list')
    # ### end Alembic commands ###
